import mongoose from "mongoose";

const ragCacheSchema = new mongoose.Schema(
  {
    from: { type: String, required: true, trim: true, lowercase: true },
    to: { type: String, required: true, trim: true, lowercase: true },
    date: { type: String, required: true, trim: true },
    classType: { type: String, default: "SL", trim: true },
    trains: { type: Array, default: [] },
  },
  { timestamps: true }
);

// TTL index: auto-delete documents 24 hours after creation
// Uses the `createdAt` field auto-generated by timestamps: true
ragCacheSchema.index({ createdAt: 1 }, { expireAfterSeconds: 86400 });
ragCacheSchema.index({ from: 1, to: 1, date: 1, classType: 1 });

export const RagCache = mongoose.model("RagCache", ragCacheSchema);
